### ISSUE TITLE
Data for US and Russia not showing up in the map

### ISSUE THREAD

**Issue by gowrijp** [sharmasw/DjangoDashboardCorona#1]
Due to some clashes in the country name given in the 2 datasets that you use the data for 2 major countries US and Russia is not showing up in the map. I believe this could be corrected by adding 2 lines in your views.py file

df3['name'] = df3['name'].replace('Russian Federation', 'Russia')
df3['name'] = df3['name'].replace('United States', 'US')

**Comment by sharmasw** [comment]
You are correct!
